name: drift_libsql
description: "Turso/Libsql database client binding for Drift"
version: 0.0.1
homepage:
repository: https://github.com/dikatok/drift_libsql
issue_tracker: https://github.com/dikatok/drift_libsql/issues

environment:
  sdk: ^3.5.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  drift: ^2.20.0
  libsql_dart: ^0.4.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
